### PR TITLE
Remember last played location

### PR DESCRIPTION
**Pull request by sharpnk**
A fix for #91. Note this is not a perfect fix, the location change is only registered when didFinishNavigation delegate is called. This means, for example, if you are watching a video in youtube, and navigated to another video within the same window, this location for the last video won't be remembered. This has more to do with the limitation of WKWebView though. I couldn't come up with a non-trivial solution to fix this now.

### CODE REVIEW

**Comment by sharpnk** [comment]
Any comments on this? It's a simple fix.

**Comment by JadenGeller** [comment]
Sorry, I didn't see this until now. Idk why.

Anyway, I'm not sure if it ought to open to the previous location. Don't OS X apps not do that by default now?

**Comment by JadenGeller** [comment]
Definitely a good idea, I was just lazy :tongue: Thanks for the fix!

**Comment by sharpnk** [comment]
You are right. This feature can actually be done with [user interface preservation](https://developer.apple.com/library/mac/documentation/General/Conceptual/MOSXAppProgrammingGuide/CoreAppDesign/CoreAppDesign.html#//apple_ref/doc/uid/TP40010543-CH3-SW26). That would be a much cleaner solution.

**Pull request closed without merging**
