### PR TITLE
Removed unnecessary NSNotificationCenter messages

### PR DESCRIPTION
**Pull request by dannyflax**
Adjusted code and storyboard to create the NSMenu items in a way which
directly calls the actions instead of passing them through the
NSNotificationCenter - Cleaned up the delegate significantly

### CODE REVIEW

**Comment by JadenGeller** [comment]
Is there any way we can maintain use of Storyboard for the menu bar?

**Comment by dannyflax** [comment]
Yeah, that was how I originally sought to achieve this (as I'm sure you did as well), but I don't think it's possible to link events across different storyboard scenes, and I am not sure how to setup the menu bar so it is not part of the delegate scene. I'll let you know if I come across a way to do so.

**Comment by dannyflax** [comment]
This solution should do the trick - I did some research on the FirstResponder chain and found what I was looking for.

**Comment by JadenGeller** [comment]
Fantastic work!! This is so much cleaner! :+1:

**Pull request merged**
