### PR TITLE
Customizable Home Page

### PR DESCRIPTION
**Pull request by benjamincongdon**
Added ability to set custom home page that is loaded whenever Helium starts.

Home page can be set within the Preferences menu, or with the hotkey `⌘,`.

Addresses #148.

### CODE REVIEW

**Comment by JadenGeller** [comment]
This seem to be missing the actual preference menu to set it, no?

**Comment by JadenGeller** [comment]
I guess I'll make the Storyboard changes myself 😄

**Comment by JadenGeller** [comment]
Thanks for building this! 🎉

**Comment by benjamincongdon** [comment]
Ah. Forgot to commit the `.storyboard` changes. 😅

**Comment by anthonyattard** [comment]
Does not seem to work in version 2.0

**Pull request merged**
