### PR TITLE
Swift 3 code conversion and focus on dialogue box on URL #185

### PR DESCRIPTION
**Pull request by alexzye**
Merges in Swift 3 code conversion and add #185

### CODE REVIEW

**Comment by scottwarren** [comment]
I'm not a contributor here, but ideally when you make pull requests, it should focus on one thing. It might be easier to get the fix for #185 merged if it was seperate to the Swift 3 code conversion ❤️

**Comment by scottwarren** [comment]
Also, it appears that this has been fixed, take a look at #188

**Comment by brorbw** [comment]
Lol - i made the exact same changes. :D

**Comment by scottwarren** [comment]
@brorbw did you make a PR? Still would be good to review, especially if it's a small PR.

**Comment by brorbw** [comment]
Not yet - there is still one other thing i have to change.

**Pull request closed without merging**
