### PR TITLE
set url user set before

### PR DESCRIPTION
**Pull request by shinriyo**
It's useful feature. Please add this feature.
But I din't test because my Version 8.2.1 Xcode can't open your project. sorry.

### CODE REVIEW

**Comment by shinriyo** [comment]
not yet?

**Comment by shinriyo** [comment]
This project already finished??

**Comment by scottwarren** [comment]
look at #188 for what I think you want to do :)

**Comment by shinriyo** [comment]
@scottwarren Thank you!

**Comment by shinriyo** [comment]
I will throw pull-request your project.
I succeeded to build your project.

**Comment by shinriyo** [comment]
`JadenGeller/Helium` is no longer update?

I hope he publish for AppStore.
https://github.com/alexzye/Helium/

**Comment by slashlos** [comment]
Try [Helium 3.0.3596](https://github.com/slashlos/Helium/releases/tag/3.0.3596).

**Comment by JadenGeller** [comment]
If I understand correctly, this implements state restoration? If so, I think we should use Cocoa-native state restoration APIs so the app respects System Preferences.

**Pull request closed without merging**
