### PR TITLE
Updated Icon

### PR DESCRIPTION
**Pull request by kgn**
I'm loving Helium! It's awesome, so I wanted to make a new icon for it so it fit in the dock better with the mac icon style. I hope you like it :)

screen shot 2015-10-25 at 5 29 40 pm

### CODE REVIEW

**Comment by JadenGeller** [comment]
I appreciate the contribution, but I going to stick with the current icon for now. People already know the app by the current colorful icon, so I think such a drastic change would hurt recognition.

**Comment by net** [comment]
@JadenGeller You should consider option to move the app to the menubar. The current icon does just a little bit out of place in El Capitan.

**Comment by JadenGeller** [comment]
That's definitely a reasonable thing to consider.

**Comment by JadenGeller** [comment]
@net Thinking a bit about it, I'm hesitant to do that. The app does not *always* float on top—it can be temporarily disabled, or the app can be hidden—without a dock icon, it is difficult for users to find the window. I think that windowed apps really ought to show in the dock.

Is the motivation for menu bar support simply hiding the icon?

**Comment by net** [comment]
@JadenGeller Think of how much functionality could be moved to the menu bar. You could move all the menus there. You could have a hide/show toggle in the menu bar menu. Then you wouldn't have to select the helium window before accessing menu actions.

**Comment by JadenGeller** [comment]
But all apps require you to select the window before accessing the menu. Why should Helium act differently in this regard?

**Comment by net** [comment]
I'm talking about this type of menu.

screen shot 2015-10-27 at 8 03 30 pm

**Comment by JadenGeller** [comment]
Transitioning to #107

**Pull request closed without merging**
