### PR TITLE
#137: Option to Hide/Show/Hover Title bar

### PR DESCRIPTION
**Pull request by lucasmorano**
Option to hide title bar as a few friends requested here https://github.com/JadenGeller/Helium/issues/137 

Three options available: Always Show (Command + Shift + G)/ Always Hide (Command + Shift + H)/ Show on Hover (Command + Shift + J)
As the image show below
http://i.imgur.com/HVcJFdP.png

### CODE REVIEW

**Comment by KrishJoshi** [comment]
Why hasn't this been merged in yet?

**Comment by lucasmorano** [comment]
@KrishJoshi I sincerely don't know hahaha

**Comment by Kikobeats** [comment]
c'mon @JadenGeller 🙏

**Comment by Deltachaos** [comment]
Would be nice if it would behave like quicktime:

screencast

**Comment by KrishJoshi** [comment]
I think @JadenGeller isn't updating this project anymore. 
@lucasmorano could you do a massive favour and merge latest from this repo into your branch and provide us with instructions how to install it.  It would be very kind of you. ☺️

**Comment by slashlos** [comment]
Well, when I started I had significantly diverged this, beyond a pull request, so I forked off [Helium](https://github.com/slashlos/Helium). This is one of those item I have done.  My goal was to mimic iTunes.  If I learn more I'll write back.

**Comment by JadenGeller** [comment]
> Would be nice if it would behave like quicktime:

I agree, but I'm not sure how to implement this.

**Comment by JadenGeller** [comment]
Closing due to age, but also this feature is now implemented!

**Pull request closed without merging**
