### PR TITLE
Helium over full-screen apps

### PR DESCRIPTION
**Pull request by itsthisjustin**
Note: Menu is now missing, need to implement MenuBar icon. Icons added
to Image assets

### CODE REVIEW

**Comment by itsthisjustin** [comment]
Needs menubar implementation like this: http://footle.org/WeatherBar/

**Comment by JadenGeller** [comment]
I can't merge this. You put a copyright notice on it.

**Comment by JadenGeller** [comment]
If you'd like to remove the copyright notice, I can definitely merge most of these changes in.

**Comment by JadenGeller** [comment]
(I didn't even realize that there was a copyright notice in the `About` menu—I'm totally cool getting rid of it all together.)

**Comment by itsthisjustin** [comment]
Definitely remove the copyright. No need for it at all.

**Comment by JadenGeller** [comment]
Cool, thanks! Could you make that commit for me and update the pull request? :smile:

**Pull request closed without merging**
